# Optional: apply only after installing your chosen Prometheus Operator.
# Configure its namespace and label selectors to select these objects.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-agent
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: cilium
  podMetricsEndpoints:
  - port: prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-operator
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      io.cilium/app: operator
  podMetricsEndpoints:
  - port: prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-envoy
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: cilium-envoy
  endpoints:
  - port: envoy-metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: hubble
  endpoints:
  - port: hubble-metrics
    interval: 30s
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: hubble-relay
  endpoints:
  - port: metrics
    interval: 30s
