apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/namespaces
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/gateway-api
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/cilium
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/network
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: cilium
  - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/dns
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: network
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/cert-manager
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: cilium
  - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pki
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/pki
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: network
  - name: pki
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./infrastructure/admin
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: gateway
  - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  path: ./apps
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: gateway
