apiVersion: v1
kind: Namespace
metadata:
  name: lan-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: administration
  labels:
    elektro.internal/route-scope: administration
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    elektro.internal/route-scope: applications
