{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "https://github.com/fluxcd/flux2/releases/download/v2.9.5/install.yaml"
  ],
  "patches": [
    {
      "target": {
        "kind": "Deployment"
      },
      "patch": "[{\"op\": \"add\", \"path\": \"/spec/template/spec/tolerations\", \"value\": [{\"key\": \"node-role.kubernetes.io/control-plane\", \"operator\": \"Exists\", \"effect\": \"NoSchedule\"}]}]"
    },
    {
      "target": {
        "kind": "Deployment",
        "name": "kustomize-controller"
      },
      "patch": "[{\"op\": \"add\", \"path\": \"/spec/template/spec/containers/0/args/-\", \"value\": \"--feature-gates=StrictPostBuildSubstitutions=true\"}]"
    }
  ]
}
